<?php

namespace Database\Seeders;

use App\Enums\UserRole;
use App\Models\Portfolio;
use App\Models\User;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Str;

class PortfolioShowcaseSeeder extends Seeder
{
    public function run(): void
    {
        $freelancer = User::where('role', UserRole::FREELANCER->value)->first();

        if (! $freelancer) {
            $freelancer = User::create([
                'name' => 'Towncore Portfolio Team',
                'username' => 'towncore_portfolio',
                'email' => 'portfolio@towncore.local',
                'phone' => '+255700000000',
                'role' => UserRole::FREELANCER,
                'password' => Hash::make('password'),
                'must_change_password' => false,
                'onboarding_completed' => true,
            ]);
        }

        $projects = [
            [
                'title' => 'Lomo Tanzania Safari Website Platform',
                'client_name' => 'Lomo Tanzania Safari',
                'project_url' => 'https://www.lomotanzaniasafari.com',
                'industry' => 'Tourism & Safari',
                'country' => 'Tanzania',
                'completion_year' => 2025,
                'duration' => '8 weeks',
                'services' => ['Web Design', 'SEO', 'Content Strategy', 'Booking UX'],
                'technologies' => ['Laravel', 'Tailwind CSS', 'MySQL'],
                'description' => 'Designed and delivered a conversion-focused safari website with destination pages, itinerary storytelling, and strong mobile performance.',
                'results' => 'Improved inquiry quality and reduced bounce rate on tour package landing pages.',
                'featured' => true,
                'item_type' => 'project',
                'is_purchasable' => false,
                'price' => null,
                'currency' => 'USD',
                'purchase_url' => null,
            ],
            [
                'title' => 'Kunjan Afrika Travel Website',
                'client_name' => 'Kunjan Afrika',
                'project_url' => 'https://kunjanafrika.com',
                'industry' => 'Travel & Hospitality',
                'country' => 'Tanzania',
                'completion_year' => 2025,
                'duration' => '6 weeks',
                'services' => ['Web Design', 'Technical SEO', 'Lead Forms'],
                'technologies' => ['Laravel', 'Alpine.js', 'Tailwind CSS'],
                'description' => 'Built a high-trust travel brand website with package showcases, gallery sections, and streamlined contact conversion points.',
                'results' => 'Increased lead submissions from organic pages and improved time-on-site for package pages.',
                'featured' => true,
                'item_type' => 'project',
                'is_purchasable' => false,
                'price' => null,
                'currency' => 'USD',
                'purchase_url' => null,
            ],
            [
                'title' => 'Safari With A Heart Commercial Website',
                'client_name' => 'Safari With A Heart',
                'project_url' => 'https://safariwithaheart.com',
                'industry' => 'Safari & Conservation Tourism',
                'country' => 'Tanzania',
                'completion_year' => 2025,
                'duration' => '7 weeks',
                'services' => ['Website Redesign', 'Booking UX', 'Performance'],
                'technologies' => ['Laravel', 'Tailwind CSS', 'MySQL'],
                'description' => 'Built a polished safari package website focused on inquiry conversion and storytelling.',
                'results' => 'Higher visitor retention and increased direct safari inquiry submissions.',
                'featured' => true,
                'item_type' => 'project',
                'is_purchasable' => false,
                'price' => null,
                'currency' => 'USD',
                'purchase_url' => null,
            ],
            [
                'title' => 'Safari With A Heart Nonprofit Portal',
                'client_name' => 'Safari With A Heart Foundation',
                'project_url' => 'https://safariwithaheart.org',
                'industry' => 'Nonprofit & Community Impact',
                'country' => 'Tanzania',
                'completion_year' => 2025,
                'duration' => '6 weeks',
                'services' => ['Donation Flow UX', 'Campaign Pages', 'SEO'],
                'technologies' => ['Laravel', 'Alpine.js', 'Tailwind CSS'],
                'description' => 'Created a mission-driven nonprofit web experience with clear donation and impact reporting sections.',
                'results' => 'Improved donor journey clarity and newsletter sign-up growth.',
                'featured' => false,
                'item_type' => 'project',
                'is_purchasable' => false,
                'price' => null,
                'currency' => 'USD',
                'purchase_url' => null,
            ],
            [
                'title' => 'Exceptional Safaries Lead-Gen Website',
                'client_name' => 'Exceptional Safaries',
                'project_url' => 'https://exceptionalsafaries.com',
                'industry' => 'Travel & Safari',
                'country' => 'Tanzania',
                'completion_year' => 2024,
                'duration' => '8 weeks',
                'services' => ['Sales Funnel Design', 'CRM-ready Forms', 'Technical SEO'],
                'technologies' => ['Laravel', 'Vite', 'MySQL'],
                'description' => 'Delivered an inquiry-first travel website with focused package pages and conversion funnel.',
                'results' => 'Increased qualified leads and reduced drop-off in the inquiry form process.',
                'featured' => false,
                'item_type' => 'project',
                'is_purchasable' => false,
                'price' => null,
                'currency' => 'USD',
                'purchase_url' => null,
            ],
            [
                'title' => 'African Queen Adventure Brand Website',
                'client_name' => 'African Queen Adventure',
                'project_url' => 'https://africanqueenadventure.com',
                'industry' => 'Adventure Tourism',
                'country' => 'Tanzania',
                'completion_year' => 2024,
                'duration' => '6 weeks',
                'services' => ['Brand Website', 'Destination Pages', 'Contact Automation'],
                'technologies' => ['Laravel', 'Blade', 'Tailwind CSS'],
                'description' => 'Designed a modern adventure site with guided package discovery and automated inquiry routing.',
                'results' => 'Improved conversion from destination pages to consultation requests.',
                'featured' => false,
                'item_type' => 'project',
                'is_purchasable' => false,
                'price' => null,
                'currency' => 'USD',
                'purchase_url' => null,
            ],
            [
                'title' => 'BrandHub TZ Commerce Website',
                'client_name' => 'BrandHub TZ',
                'project_url' => 'https://brandhub.tz',
                'industry' => 'Printing & Design',
                'country' => 'Tanzania',
                'completion_year' => 2025,
                'duration' => '9 weeks',
                'services' => ['Ecommerce Setup', 'Catalog UX', 'Order Workflow'],
                'technologies' => ['Laravel', 'Livewire', 'MySQL'],
                'description' => 'Built an online catalog and ordering experience for mugs, T-shirts, branded prints, and design services.',
                'results' => 'Faster quote turnaround and improved order conversion for custom products.',
                'featured' => false,
                'item_type' => 'project',
                'is_purchasable' => false,
                'price' => null,
                'currency' => 'USD',
                'purchase_url' => null,
            ],
            [
                'title' => 'Makando Car Hire Booking Website',
                'client_name' => 'Makando Car Hire',
                'project_url' => 'https://makandocarhire.com',
                'industry' => 'Transport & Car Rental',
                'country' => 'Tanzania',
                'completion_year' => 2025,
                'duration' => '7 weeks',
                'services' => ['Fleet Listing UX', 'Booking Requests', 'SEO Setup'],
                'technologies' => ['Laravel', 'Tailwind CSS', 'MySQL'],
                'description' => 'Developed a booking-focused car hire website with clear fleet details and reservation workflow.',
                'results' => 'Improved booking form completion and reduced inquiry response time.',
                'featured' => false,
                'item_type' => 'project',
                'is_purchasable' => false,
                'price' => null,
                'currency' => 'USD',
                'purchase_url' => null,
            ],
            [
                'title' => 'MediCore Hospital Management System',
                'client_name' => 'Towncore Product Suite',
                'project_url' => null,
                'industry' => 'Healthcare',
                'country' => 'Global',
                'completion_year' => 2026,
                'duration' => 'SaaS License',
                'services' => ['Patient Records', 'Billing', 'Appointments', 'Pharmacy'],
                'technologies' => ['Laravel', 'Vue.js', 'MySQL', 'REST API'],
                'description' => 'Complete hospital information system with EMR workflows, appointment scheduling, billing, pharmacy, and role-based access.',
                'results' => 'Helps hospitals streamline patient flow, reduce paperwork, and improve service delivery.',
                'featured' => true,
                'item_type' => 'product',
                'is_purchasable' => true,
                'price' => 2499.00,
                'currency' => 'USD',
                'purchase_url' => 'mailto:sales@towncore.local?subject=Purchase%20MediCore%20Hospital%20Management%20System',
            ],
            [
                'title' => 'ExamFlow School Examination System',
                'client_name' => 'Towncore Product Suite',
                'project_url' => null,
                'industry' => 'Education',
                'country' => 'Global',
                'completion_year' => 2026,
                'duration' => 'SaaS License',
                'services' => ['Exam Authoring', 'Auto Marking', 'Result Analytics', 'Report Cards'],
                'technologies' => ['Laravel', 'Livewire', 'MySQL'],
                'description' => 'School examination platform for question banks, timed assessments, grading, and detailed performance reporting.',
                'results' => 'Saves exam administration time and improves accuracy of grading and student performance insights.',
                'featured' => true,
                'item_type' => 'product',
                'is_purchasable' => true,
                'price' => 1499.00,
                'currency' => 'USD',
                'purchase_url' => 'mailto:sales@towncore.local?subject=Purchase%20ExamFlow%20School%20Examination%20System',
            ],
            [
                'title' => 'TouriDesk Tourism SaaS & Ticket Booking Suite',
                'client_name' => 'Towncore Product Suite',
                'project_url' => null,
                'industry' => 'Tourism Technology',
                'country' => 'Global',
                'completion_year' => 2026,
                'duration' => 'SaaS License',
                'services' => ['Tour Packages', 'Ticket Booking', 'Payment Tracking', 'Customer CRM'],
                'technologies' => ['Laravel', 'Alpine.js', 'MySQL', 'API Integrations'],
                'description' => 'All-in-one tourism SaaS for agencies handling package sales, ticket inventory, customer records, and booking operations.',
                'results' => 'Improves booking management, reduces operational overhead, and speeds up customer response.',
                'featured' => true,
                'item_type' => 'product',
                'is_purchasable' => true,
                'price' => 1899.00,
                'currency' => 'USD',
                'purchase_url' => 'mailto:sales@towncore.local?subject=Purchase%20TouriDesk%20Tourism%20SaaS%20Suite',
            ],
            [
                'title' => 'SecureVault Password Store App',
                'client_name' => 'Towncore Product Suite',
                'project_url' => null,
                'industry' => 'Cybersecurity',
                'country' => 'Global',
                'completion_year' => 2026,
                'duration' => 'SaaS License',
                'services' => ['Encrypted Vault', 'Team Sharing', 'Audit Logs', '2FA Security'],
                'technologies' => ['Laravel', 'Vue.js', 'AES Encryption'],
                'description' => 'Secure password management app for teams with encryption, access controls, and audit visibility.',
                'results' => 'Reduces credential leaks and centralizes secure password governance.',
                'featured' => false,
                'item_type' => 'product',
                'is_purchasable' => true,
                'price' => 699.00,
                'currency' => 'USD',
                'purchase_url' => 'mailto:sales@towncore.local?subject=Purchase%20SecureVault%20Password%20Store%20App',
            ],
            [
                'title' => 'CivicVote Digital Voting System',
                'client_name' => 'Towncore Product Suite',
                'project_url' => null,
                'industry' => 'Governance & Associations',
                'country' => 'Global',
                'completion_year' => 2026,
                'duration' => 'SaaS License',
                'services' => ['Voter Registry', 'Ballot Management', 'Results Dashboard', 'Audit Trails'],
                'technologies' => ['Laravel', 'Livewire', 'MySQL'],
                'description' => 'Secure digital voting platform for organizations, cooperatives, and associations requiring transparent elections.',
                'results' => 'Improves election transparency and speeds up result publication.',
                'featured' => false,
                'item_type' => 'product',
                'is_purchasable' => true,
                'price' => 1299.00,
                'currency' => 'USD',
                'purchase_url' => 'mailto:sales@towncore.local?subject=Purchase%20CivicVote%20Digital%20Voting%20System',
            ],
            [
                'title' => 'DataHub Enterprise Data Management System',
                'client_name' => 'Towncore Product Suite',
                'project_url' => null,
                'industry' => 'Business Operations',
                'country' => 'Global',
                'completion_year' => 2026,
                'duration' => 'SaaS License',
                'services' => ['Document Registry', 'Records Workflow', 'Permissions', 'Advanced Search'],
                'technologies' => ['Laravel', 'Elasticsearch', 'MySQL'],
                'description' => 'A structured data and records management solution for organizations managing high volumes of business documents.',
                'results' => 'Improves data governance and reduces time spent retrieving records.',
                'featured' => false,
                'item_type' => 'product',
                'is_purchasable' => true,
                'price' => 1599.00,
                'currency' => 'USD',
                'purchase_url' => 'mailto:sales@towncore.local?subject=Purchase%20DataHub%20Data%20Management%20System',
            ],
        ];

        foreach ($projects as $project) {
            Portfolio::updateOrCreate(
                ['title' => $project['title']],
                [
                    'user_id' => $freelancer->id,
                    'slug' => Str::slug($project['title']),
                    'description' => $project['description'],
                    'client_name' => $project['client_name'],
                    'project_url' => $project['project_url'],
                    'industry' => $project['industry'],
                    'country' => $project['country'],
                    'completion_year' => $project['completion_year'],
                    'duration' => $project['duration'],
                    'services' => $project['services'],
                    'technologies' => $project['technologies'],
                    'results' => $project['results'],
                    'featured' => $project['featured'],
                    'item_type' => $project['item_type'],
                    'is_purchasable' => $project['is_purchasable'],
                    'price' => $project['price'],
                    'currency' => $project['currency'],
                    'purchase_url' => $project['purchase_url'],
                    'status' => 'approved',
                ]
            );
        }
    }
}
